export const styles = {
  pagina: {
    width: '100vw',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    background: 'linear-gradient(180deg, #0B8236 0%, #00C86F 100%)',
    padding: '20px',
    boxSizing: 'border-box',
  },
  tarjeta: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: '420px',
    backgroundColor: '#ffffff',
    borderRadius: '20px',
    padding: '40px 35px',
    boxShadow: '0 10px 40px rgba(0,0,0,0.25)',
    boxSizing: 'border-box',
  },
  logoWrapper: {
    width: '130px',
    height: '130px',
    borderRadius: '50%',
    border: '4px solid #000',
    backgroundColor: '#fff',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    marginBottom: '18px',
  },
  logo: {
    width: '90%',
    height: '90%',
    objectFit: 'contain',
  },
  nombreHospital: {
    color: '#0B8236',
    fontSize: '26px',
    fontWeight: 700,
    textAlign: 'center',
    margin: 0,
  },
  eslogan: {
    color: '#5f6b6d',
    fontSize: '14px',
    textAlign: 'center',
    fontWeight: 400,
    marginTop: '4px',
    marginBottom: '28px',
    letterSpacing: '0.3px',
  },
  formulario: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  tituloForm: {
    color: '#1c2b2f',
    fontSize: '22px',
    marginBottom: '20px',
    fontWeight: 700,
    textAlign: 'center',
  },
  cajaTexto: {
    width: '100%',
    padding: '13px 18px',
    fontSize: '15px',
    borderRadius: '10px',
    border: '1.5px solid #d7dcdd',
    backgroundColor: '#f7f9f9',
    marginBottom: '16px',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#1c2b2f',
  },
  botonContinuar: {
    padding: '13px 40px',
    fontSize: '16px',
    borderRadius: '10px',
    border: 'none',
    background: 'linear-gradient(90deg, #0B8236, #00C86F)',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 700,
    marginTop: '6px',
    boxShadow: '0 4px 10px rgba(11,130,54,0.3)',
    transition: 'opacity 0.2s ease',
  },
  botonBloqueado: {
    padding: '13px 40px',
    fontSize: '16px',
    borderRadius: '10px',
    border: 'none',
    backgroundColor: '#b0b6b6',
    color: '#eee',
    cursor: 'not-allowed',
    fontWeight: 700,
    marginTop: '6px',
  },
  errorText: {
    color: '#c0392b',
    marginBottom: '16px',
    fontWeight: 600,
    textAlign: 'center',
    backgroundColor: '#fdecea',
    padding: '10px',
    borderRadius: '8px',
    width: '100%',
    fontSize: '14px',
    boxSizing: 'border-box',
  }
};